### ISSUE TITLE
Flask for backend or something else?

### ISSUE THREAD

**Issue by patrickpierson** [AWSFrederick/Spires-Export#4]
@mblayman mentioned he doesnt have much work with Flask and I am not partial to it.  I created a flask-app to test some of the endpoints but it doesn't seem to hold up well in AWS behind a loadbalancer without some tuning https://stackoverflow.com/questions/16444190/flask-application-timeout-with-amazon-load-balancer

Ideas?

**Comment by mblayman** [comment]
@patrickpierson and I are going to spike on a Django version tomorrow to see if that will fit the bill.

**Comment by patrickpierson** [comment]
Awesome hangout today. I'm thinking about scheduling these regularly.

**Comment by patrickpierson** [comment]
Going with django
